"""add media table, drop story media_url

Revision ID: 30bd8c97faa2
Revises: a106aaade90a
Create Date: 2026-06-15 09:29:05.017001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30bd8c97faa2'
down_revision: Union[str, Sequence[str], None] = 'a106aaade90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_story_id'), ['story_id'], unique=False)

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_story_id'))
        batch_op.drop_index(batch_op.f('ix_media_id'))

    op.drop_table('media')
    # ### end Alembic commands ###
