"""add categories table

Revision ID: 4a5c8d0c4370
Revises: dfcadd3915a4
Create Date: 2026-06-15 09:56:53.588675

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5c8d0c4370'
down_revision: Union[str, Sequence[str], None] = 'dfcadd3915a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###

    # seed the categories that the app already uses (slugs match existing stories)
    categories_table = sa.table(
        "categories",
        sa.column("slug", sa.String),
        sa.column("label", sa.String),
        sa.column("description", sa.Text),
        sa.column("icon", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("created_at", sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(
        categories_table,
        [
            {"slug": "heritage", "label": "Heritage", "description": None,
             "icon": "bi-journal-bookmark", "sort_order": 1, "created_at": now},
            {"slug": "landmarks", "label": "Landmarks", "description": None,
             "icon": "bi-bank2", "sort_order": 2, "created_at": now},
            {"slug": "oral", "label": "Oral Histories", "description": None,
             "icon": "bi-mic-fill", "sort_order": 3, "created_at": now},
            {"slug": "customs", "label": "Customs", "description": None,
             "icon": "bi-stars", "sort_order": 4, "created_at": now},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
