"""add story user_id and is_anonymous

Revision ID: dfcadd3915a4
Revises: 30bd8c97faa2
Create Date: 2026-06-15 09:39:38.230794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcadd3915a4'
down_revision: Union[str, Sequence[str], None] = '30bd8c97faa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index(batch_op.f('ix_stories_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_stories_user_id_users', 'users', ['user_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stories_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stories_user_id'))
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
